name: NPM 发布

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
    tags:
      - '*'  # 当打 tag 时触发

jobs:
  release:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 作为运行环境

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # 根据项目需求修改 Node.js 版本
          registry-url: 'https://registry.npmjs.org/'

      - name: 安装依赖
        run: npm install

      - name: 确定发布的版本号
        id: versioning
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/heads/main ]]; then
            # 从 main 分支的提交中生成预发布版本
            echo "::set-output name=version::$(npm version prerelease --no-git-tag-version)"
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/* ]]; then
            # 如果是打 tag，则使用打好的 tag 作为发布的版本
            echo "::set-output name=version::$(npm version from-git --no-git-tag-version)"
          fi

      - name: 更新 package.json 中的版本号
        run: |
          npm version ${{ steps.versioning.outputs.version }} --no-git-tag-version

      - name: 发布到 NPM（main 分支的预发布版本）
        if: github.ref == 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # 使用 NPM 的认证 token
        run: npm publish --tag prerelease

      - name: 发布到 NPM（使用 tag 的正式版本发布）
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # 使用 NPM 的认证 token
        run: npm publish
