name: 发布到npm

on:
  push:
    branches:
      - main
  create:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码库
      uses: actions/checkout@v2

    - name: 设置Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org'

    - name: 安装依赖
      run: npm install

    - name: 构建项目
      run: npm run build

    - name: 更新版本并提交
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
          npm version prerelease --preid=beta --no-git-tag-version
        elif [ "${{ github.event_name }}" == "create" ]; then
          npm version patch --no-git-tag-version
        fi
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add package.json
        git commit -m "chore: 更新版本到 $(jq -r .version < package.json)"
        git push

    - name: 发布到npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        VERSION=$(jq -r .version < package.json)
        if [ "${{ github.event_name }}" == "push" ]; then
          npm publish --tag beta
        elif [ "${{ github.event_name }}" == "create" ]; then
          npm publish
        fi